FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package and lock files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Run the development server
CMD ["npm", "run", "dev"]